name: Pull Request

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    uses: stakater/.github/.github/workflows/pull_request_container_build.yaml@v0.0.131
    with:
      DOCKER_FILE_PATH: Dockerfile
    secrets:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      CONTAINER_REGISTRY_USERNAME: ${{ github.actor }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
