name: Push

on:
  push:
    branches:
      - 'main'

jobs:
  push:
    uses: stakater/.github/.github/workflows/push_container.yaml@v0.0.52
    with:
      DOCKER_FILE_PATH: Dockerfile
      RELEASE_BRANCH: main
    secrets:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      CONTAINER_REGISTRY_USERNAME: ${{ github.actor }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
      GH_TOKEN: ${{ secrets.STAKATER_GITHUB_TOKEN }}
